services:
  api:
    container_name: flask-api
    build:
      context: ./api
      target: base
    ports:
      - 5000:5000
    tty: true
    volumes:
      - ./api:/workspace:cached
    env_file:
      - ./api/.env
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json